protected/modules/finanzas/models/MovimientosCuenta.php
<?php
/**
 * Contiene todos los movimientos financieros ejecutados en una cuenta en particular para una entidad en particular.
 *
 * Permite obtener una lista con las entregas, transferencias, solicitudes de presupuestos aceptadas y recibos
 * (recuperaciones de gastos y vales a rendir) realizadas en una cuenta en particular para una entidad en particular.
 * La totalidad de los movimientos son ordenados por la fecha de la transaccion y poseen el siguiente formato:
 * <ul>
 *  <li>ID movimiento</li>
 *  <li>Fecha de la transferencia</li>
 *  <li>Operador a cargo</li>
 *  <li>Entidad de origen</li>
 *  <li>Cuenta de origen</li>
 *  <li>Entidad de destino</li>
 *  <li>Cuenta de destino</li>
 *  <li>Monto</li>
 *  <li>Saldo</li>
 * </ul>
 * Para obtener los movimientos de una cuenta es necesario especificar tanto el id de la cuenta como la entidad a buscar,
 * @example <br />
 *  $movimientos = new MovimientosCuenta($id_cuenta,$entidad);<br />
 *  $movimientos->cargarMovimientos();<br />
 * @version   0.01
 * @since     31/12/2012
 * @author    dacuna <diego.acuna@usm.cl>
 */
class MovimientosCuenta extends CComponent
{
    private $cuenta;
    private $id;
    private $fecha_transferencia;
    private $operador;
    private $origen;
    private $cuenta_origen;
    private $destino;
    private $cuenta_destino;
    private $monto;
    private $saldo;
    private $entidad;
    private $operacion;

    public function __construct($cuenta,$entidad){
        $this->entidad=$entidad;
        $this->cuenta=$cuenta;
    }

    public function cargarMovimientos(){
        $cuenta=$this->cuenta;
        $entidad=$this->entidad;
        $movimientos=array();
        //se deben cargar las entregas, luego las transferencias y luego los cargos en presupuestos y recibos
        $entregas=Entrega::model()->findAll('id_cuenta=:ic AND (id_entidad=:ie and tipo_entidad=:te)
            OR (id_entidad_origen=:ie and tipo_entidad_origen=:te) order by fecha_entrega DESC',array(
            ':ic'=>$cuenta,':ie'=>$entidad->getId(),':te'=>$entidad->getTipoEntidadNumerico()
        ));
        foreach ($entregas as $entrega) {
            $movimiento=new MovimientosCuenta($cuenta,$entidad);
            $movimiento->setId($entrega->id);
            $movimiento->setFechaTransferencia($entrega->fecha_entrega);
            $movimiento->setOperador($entrega->operador);
            $movimiento->setOrigen($entrega->getEntidadOrigen());
            $movimiento->setCuentaOrigen($entrega->cuenta);
            $movimiento->setDestino($entrega->getEntidad());
            $movimiento->setCuentaDestino($entrega->cuenta);
            $movimiento->setMonto($entrega->monto);
            $movimiento->setOperacion(0);
            $movimientos[]=$movimiento;
        }


        $transferencias=Transferencia::model()->findAll('(id_cuenta_origen=:ic OR id_cuenta_destino=:ic) AND
            ((id_entidad_origen=:ie and tipo_entidad_origen=:te) OR (id_entidad_destino=:ie and tipo_entidad_destino=:te))
              order by fecha_transferencia DESC',array(
            ':ic'=>$cuenta,':ie'=>$entidad->getId(),':te'=>$entidad->getTipoEntidadNumerico()
        ));

        foreach ($transferencias as $transferencia) {
            $movimiento=new MovimientosCuenta($cuenta,$entidad);
            $movimiento->setId($transferencia->id);
            $movimiento->setFechaTransferencia($transferencia->fecha_transferencia);
            $movimiento->setOperador($transferencia->operador);
            $movimiento->setOrigen($transferencia->getEntidadOrigen());
            $movimiento->setCuentaOrigen($transferencia->cuenta_origen);
            $movimiento->setDestino($transferencia->getEntidadDestino());
            $movimiento->setCuentaDestino($transferencia->cuenta_destino);
            $movimiento->setMonto($transferencia->monto);
            $movimiento->setOperacion(0);
            $movimientos[]=$movimiento;
        }

        $presupuestos=Presupuesto::model()->findAll('id_cuenta=:ic AND id_entidad=:ie AND tipo_entidad=:te AND (estado=1 or estado=2)
            order by fecha_accion_realizada DESC',array(
            ':ic'=>$cuenta,':ie'=>$entidad->getId(),':te'=>$entidad->getTipoEntidadNumerico()
        ));

        foreach ($presupuestos as $presupuesto) {
            $movimiento=new MovimientosCuenta($cuenta,$entidad);
            $movimiento->setId($presupuesto->id);
            $movimiento->setFechaTransferencia($presupuesto->fecha_accion_realizada);
            $movimiento->setOperador($presupuesto->solicitante);
            $movimiento->setOrigen($presupuesto->getEntidad());
            $movimiento->setCuentaDestino("Solicitud de Presupuesto");
            $movimiento->setDestino($presupuesto->detalle);
            $movimiento->setCuentaOrigen($presupuesto->cuenta);
            $movimiento->setMonto($presupuesto->totalMontoItems);
            $movimiento->setOperacion(1);
            $movimientos[]=$movimiento;
        }

        $recibos=Recibo::model()->findAll('codigo_presupuestario=:ic AND id_entidad=:ie AND tipo_entidad=:te AND estado=1
            order by fecha_emision_documento DESC',array(
            ':ic'=>$cuenta,':ie'=>$entidad->getId(),':te'=>$entidad->getTipoEntidadNumerico()
        ));

        foreach ($recibos as $recibo) {
            //por cada recibo hay un abono en la cuenta igual al total del presupuesto de dicho recibo
            $movimiento=new MovimientosCuenta($cuenta,$entidad);
            $movimiento->setId('P'.$recibo->id);
            $movimiento->setFechaTransferencia($recibo->fecha_emision_documento);
            $movimiento->setOperador($recibo->solicitante);
            $movimiento->setOrigen($recibo->getEntidad());
            $movimiento->setCuentaDestino($recibo->codigoPresupuestario);
            $movimiento->setDestino($recibo->getEntidad());
            $movimiento->setCuentaOrigen("Presupuesto recibo {$recibo->id}");
            $movimiento->setMonto($recibo->totalMontoItemsPresupuestos);
            $movimiento->setOperacion(3);
            $movimientos[]=$movimiento;

            $movimiento=new MovimientosCuenta($cuenta,$entidad);
            $movimiento->setId($recibo->id);
            $movimiento->setFechaTransferencia($recibo->fecha_emision_documento);
            $movimiento->setOperador($recibo->solicitante);
            $movimiento->setOrigen($recibo->getEntidad());
            $movimiento->setCuentaDestino($recibo->tipoRecibo);
            $movimiento->setDestino($recibo->nota);
            $movimiento->setCuentaOrigen($recibo->codigoPresupuestario);
            $movimiento->setMonto($recibo->monto_vale);
            $movimiento->setOperacion(2);
            $movimientos[]=$movimiento;
        }

        usort($movimientos, "self::sortMovimientos");

        //se deben cargar los saldos
        $i=0;
        $saldo_anterior=0;
        foreach ($movimientos as $movimiento) {
            if($i==0){//el primer movimiento es el primer valor de la cuenta, siempre es el primer saldo
                $movimiento->setSaldo($movimiento->getMonto());
            }
            else{
                if($movimiento->operacion!=0){
                    if($movimiento->operacion==3) //es el cargo de un presupuesto
                        $movimiento->setSaldo($saldo_anterior+$movimiento->getMonto());
                    else //le saque para un presupuesto o un recibo
                        $movimiento->setSaldo($saldo_anterior-$movimiento->getMonto());
                }else{
                    if($movimiento->getCuentaDestino()->id==$cuenta){
                        //es un abono
                        $movimiento->setSaldo($saldo_anterior+$movimiento->getMonto());
                    }else{
                        //es un cargo
                        $movimiento->setSaldo($saldo_anterior-$movimiento->getMonto());
                    }
                }
            }
            $saldo_anterior=$movimiento->getSaldo();
            $i++;
        }

        return array_reverse($movimientos);
    }

    private function sortMovimientos($a, $b)
    {
        if ($a->fecha_transferencia == $b->fecha_transferencia) {
            return 0;
        }
        return ($a->fecha_transferencia < $b->fecha_transferencia) ? -1 : 1;
    }

    public function setCuentaDestino($cuenta_destino)
    {
        $this->cuenta_destino = $cuenta_destino;
    }

    public function getCuentaDestino()
    {
        return $this->cuenta_destino;
    }

    public function setCuentaOrigen($cuenta_origen)
    {
        $this->cuenta_origen = $cuenta_origen;
    }

    public function getCuentaOrigen()
    {
        return $this->cuenta_origen;
    }

    public function setDestino($destino)
    {
        $this->destino = $destino;
    }

    public function getDestino()
    {
        return $this->destino;
    }

    public function setFechaTransferencia($fecha_transferencia)
    {
        $this->fecha_transferencia = $fecha_transferencia;
    }

    public function getFechaTransferencia()
    {
        return $this->fecha_transferencia;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getId()
    {
        return $this->id;
    }

    public function setMonto($monto)
    {
        $this->monto = $monto;
    }

    public function getMonto()
    {
        return $this->monto;
    }

    public function setOperador($operador)
    {
        $this->operador = $operador;
    }

    public function getOperador()
    {
        return $this->operador;
    }

    public function setOrigen($origen)
    {
        $this->origen = $origen;
    }

    public function getOrigen()
    {
        return $this->origen;
    }

    public function setSaldo($saldo)
    {
        $this->saldo = $saldo;
    }

    public function getSaldo()
    {
        return $this->saldo;
    }

    public function setEntidad($entidad)
    {
        $this->entidad = $entidad;
    }

    public function getEntidad()
    {

protected/modules/finanzas/controllers/HistoricoController.php
<?php
Yii::import('application.modules.usuarios.components.Entidad');
/**
 * Controlador que contiene las acciones para desplegar los datos historicos de cuentas y movimientos
 * de entidades en el sistema.
 *
 * @version   1.0
 * @since     10/11/12
 * @author    dacuna <dacuna@dacuna.me>
 */
class HistoricoController extends Controller
{
    /**
     * Muestra un resumen de todas las entregas realizadas recientemente. Es solo util para
     * fines administrativos, ya que las entidades solo ven un detalle de todos los movimientos
     * de sus cuentas (entregas + transferencias).
     *
     * @return  void
     */
    public function actionEntregas(){
        $dataProvider=new CActiveDataProvider('Entrega', array(
            'criteria'=>array(
                //'condition'=>'valida=1',
                'order'=>'fecha_entrega DESC'
            ),
            'pagination'=>array(
                'pageSize'=>20,
            ),
        ));

        $this->render('entregas',array(
            'dataProvider'=>$dataProvider
        ));
    }

    /**
     * Muestra un resumen de todas las transferencias realizadas recientemente. Es solo util para
     * fines administrativos, ya que las entidades solo ven un detalle de todos los movimientos
     * de sus cuentas (entregas + transferencias).
     *
     * @return  void
     */
    public function actionTransferencias(){
        $dataProvider=new CActiveDataProvider('Transferencia', array(
            'criteria'=>array(
                //'condition'=>'valida=1',
                'order'=>'fecha_transferencia DESC'
            ),
            'pagination'=>array(
                'pageSize'=>20,
            ),
        ));

        $this->render('transferencias',array(
            'dataProvider'=>$dataProvider
        ));
    }

    /**
     * Accion que despliega todos las transferencias realizados en una cuenta en una determinada entidad.
     * Esta accion es la que realmente permite a los usuarios del sistema ver que esta pasando con sus
     * cuentas. Para esto se deben unificar los movimientos de transferencias y transferencias internas
     * dentro del sistema.
     *
     * @param int $id id de la entidad
     * @param int $tipo tipo de la entidad
     *
     * @return  void
     * @todo VERIFICAR PERMISOS DE QUE LA PERSONA QUE VE ESTA ACCION PUEDE VER LA CUENTA DE LA ENTIDAD!!!
     */
    public function actionVerTransferenciasEntidad($id,$tipo){
        $entidad = new Entidad($id, $tipo);

        //transferencias recibidas: entregas que ha recibido la entidad
        $recibidas=new CActiveDataProvider('Entrega', array(
            'criteria'=>array(
                'condition'=>'id_entidad=:id and tipo_entidad=:tipo',
                'params'=>array(':id'=>$entidad->getId(),':tipo'=>$entidad->getTipoEntidadNumerico()),
                'order'=>'fecha_entrega DESC'
            ),
            'pagination'=>array(
                'pageSize'=>20,
            ),
        ));

        $enviadas=new CActiveDataProvider('Entrega', array(
            'criteria'=>array(
                'condition'=>'id_entidad_origen=:id and tipo_entidad_origen=:tipo',
                'params'=>array(':id'=>$entidad->getId(),':tipo'=>$entidad->getTipoEntidadNumerico()),
                'order'=>'fecha_entrega DESC'
            ),
            'pagination'=>array(
                'pageSize'=>20,
            ),
        ));

        $internas=new CActiveDataProvider('Transferencia', array(
            'criteria'=>array(
                'condition'=>'(id_entidad_origen=:id and tipo_entidad_origen=:tipo) OR
                              (id_entidad_destino=:id and tipo_entidad_destino=:tipo)',
                'params'=>array(':id'=>$entidad->getId(),':tipo'=>$entidad->getTipoEntidadNumerico()),
                'order'=>'fecha_transferencia DESC'
            ),
            'pagination'=>array(
                'pageSize'=>20,
            ),
        ));

        $this->render('transferencias_entidad',array(
            'enviadas'=>$enviadas,
            'recibidas'=>$recibidas,
            'internas'=>$internas,
            'entidad'=>$entidad
        ));

    }

    /**
     * Accion que despliega todos los movimientos realizados en una cuenta en una determinada entidad.
     * Esta accion es la que realmente permite a los usuarios del sistema ver que esta pasando con sus
     * cuentas. Para esto se deben unificar los movimientos de transferencias y transferencias internas
     * dentro del sistema. Para esto se utiliza la clase @link{MovimientosCuenta} que encapsula la logica
     * para obtener todos los movimientos.
     *
     * @param int $c id de la cuenta
     * @param int $id id de la entidad
     * @param int $tipo tipo de la entidad
     *
     * @return  void
     * @todo VERIFICAR PERMISOS DE QUE LA PERSONA QUE VE ESTA ACCION PUEDE VER LA CUENTA DE LA ENTIDAD!!!
     */
    public function actionMovimientosCuenta($c,$id,$tipo){
        $entidad = new Entidad($id, $tipo);
        $cuenta=Cuenta::model()->findByPk($c);
        $movimientos=new MovimientosCuenta($cuenta->id,$entidad);
        $movimientos_all=$movimientos->cargarMovimientos();

        $this->render('movimientos_cuenta',array(
            'entidad'=>$entidad,
            'movimientos'=>$movimientos_all,
            'cuenta'=>$cuenta
        ));
    }

    /**
     * Filtros del controlador.
     *
     * @return  array filtros del controlador.
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Reglas de acceso del controladr.
     *
     * @return  array reglas de acceso del controlador.
     */
    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('entregas','transferencias'),
                'roles'=>array('administrador'),
            ),
            array('allow',
                'actions'=>array('verTransferenciasEntidad','movimientosCuenta'),
                'roles'=>array('usuario'),
            ),
            array('deny',
                'users'=>array('*'),
            ),
        );
    }
}

protected/modules/finanzas/views/historico/entregas.php
<?php
$this->pageTitle = 'Hist&oacute;rico de entregas';
$this->breadcrumbs=array(
    'Hist&oacute;rico de entregas'
);
?>

<dl class="nice contained tabs">
    <dd><a href="#" class="active">Hist&oacute;rico de entregas</a></dd>
</dl>

<ul class="nice tabs-content contained">
    <li class="active" id="crear-cuenta">
        <div class="panel clearfix">
            <h5>Hist&oacute;rico de entregas</h5>
            <p>A continuaci&oacute;n se presentan las &uacute;ltimas entregas de fondos realizadas:</p>

            <?php
                $this->widget('zii.widgets.grid.CGridView', array(
                    'dataProvider'=>$dataProvider,
                    'columns'=>array(
                    'id',          // display the 'title' attribute
                    array('name'=>'Cuenta de origen','value'=>'$data->cuenta->identificador'),  // display the 'name' attribute of the 'category' relation
                    'monto',   // display the 'content' attribute as purified HTML
                    array('name'=>'Iniciativa/Proyecto destino','value'=>'$data->entidad->tipoEntidad.": ".$data->entidad->nombre'),
                    array(            // display 'author.username' using an expression
                        'name'=>'Fecha de entrega',
                        'value'=>'app()->dateFormatter->format("dd\'/\'MM\'/\'y",$data->fecha_entrega)'),
                    ),
                 ));
            ?>
        </div>

    </li>
</ul>

protected/modules/finanzas/views/historico/movimientos_cuenta.php
<?php
$this->pageTitle = 'Movimientos';
$this->breadcrumbs=array(
    $entidad->tipoEntidad=>array($entidad->urlEntidad(),'id'=>$entidad->id),
    $entidad->getNombre()=>array($entidad->urlEntidad(),'id'=>$entidad->id),
    'Cuentas'=>array('/finanzas/crud/verCuentasEntidad','id'=>$entidad->id,'tipo'=>$entidad->getTipoEntidadNumerico()),
    'Movimientos'
);
?>

<dl class="nice contained tabs">
    <dd><a href="#" class="active">Movimientos</a></dd>
</dl>

<ul class="nice tabs-content contained">
    <li class="active" id="crear-cuenta">
        <div class="panel clearfix">
            <h5>Movimientos cuenta <?php echo $cuenta->identificador;?></h5>

            <div class="grid-view">
            <table class="items">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Fecha de transferencia</th>
                    <th>Operador</th>
                    <th>Cuenta origen</th>
                    <th>Origen</th>
                    <th>Cuenta destino/Operaci&oacute;n</th>
                    <th>Destino/Detalle</th>
                    <th>Monto</th>
                    <th>Saldo</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($movimientos as $movimiento):?>
                <tr>
                    <td style="text-align:right;"><?php echo $movimiento->id;?></td>
                    <td style="text-align:center;"><?php echo app()->dateFormatter->format("dd'/'MM'/'y",$movimiento->fechaTransferencia);?></td>
                    <td style="text-align:center;"><?php echo $movimiento->operador->nombrePresentacion;?></td>
                    <td>
                        <?php if($movimiento->operacion!=3):?>
                        <?php echo $movimiento->cuentaOrigen->identificador;?>
                        <?php else:?>
                        <?php echo $movimiento->cuentaOrigen;?>
                        <?php endif;?>
                    </td>
                    <td style="text-align:center;"><?php echo $movimiento->origen->getNombre();?></td>
                    <td style="text-align:center;">
                        <?php if($movimiento->operacion==0 ||$movimiento->operacion==3):?>
                        <?php echo $movimiento->cuentaDestino->identificador;?>
                        <?php else:?>
                        <?php echo $movimiento->cuentaDestino;?>
                        <?php endif;?>
                    </td>
                    <td>
                        <?php if($movimiento->operacion==0 || $movimiento->operacion==3):?>
                            <?php echo $movimiento->destino->getNombre();?>
                        <?php else:?>
                            <?php echo $movimiento->destino;?>
                        <?php endif;?>
                    </td>
                    <td style="text-align: right;">$<?php echo app()->NumberFormatter->formatDecimal($movimiento->monto);?></td>
                    <td style="text-align: right;">$<?php echo app()->NumberFormatter->formatDecimal($movimiento->saldo);?></td>
                </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
            </div>

        </div>

    </li>
</ul>
<?php
$baseScriptUrl=Yii::app()->getAssetManager()->publish(Yii::getPathOfAlias('zii.widgets.assets')).'/gridview';
$cssFile=$baseScriptUrl.'/styles.css';
Yii::app()->getClientScript()->registerCssFile($cssFile);
?>

protected/modules/finanzas/views/historico/transferencias.php
<?php
$this->pageTitle = 'Hist&oacute;rico de transferencias';
$this->breadcrumbs=array(
    'Hist&oacute;rico de transferencias'
);
?>

<dl class="nice contained tabs">
    <dd><a href="#" class="active">Hist&oacute;rico de transferencias</a></dd>
</dl>

<ul class="nice tabs-content contained">
    <li class="active" id="crear-cuenta">
        <div class="panel clearfix">
            <h5>Hist&oacute;rico de transferencias</h5>
            <p>A continuaci&oacute;n se presentan las &uacute;ltimas transferencias de fondos realizadas:</p>

            <?php
                $this->widget('zii.widgets.grid.CGridView', array(
                    'dataProvider'=>$dataProvider,
                    'columns'=>array(
                    'id',
                    array('name'=>'Cuenta origen','value'=>'$data->cuenta_origen->nombre'),
                    array('name'=>'Cuenta destino','value'=>'$data->cuenta_destino->nombre'),
                    'monto',
                    array(
                        'name'=>'Fecha transferencia',
                        'value'=>'app()->dateFormatter->format("dd\'/\'MM\'/\'y",$data->fecha_transferencia)'),
                    ),
                 ));
            ?>
        </div>

    </li>
</ul>

protected/modules/finanzas/views/historico/transferencias_entidad.php
<?php
$this->pageTitle = 'Hist&oacute;rico de transferencias';
$this->breadcrumbs=array(
    $entidad->tipoEntidad=>array($entidad->urlEntidad(),'id'=>$entidad->id),
    $entidad->getNombre()=>array($entidad->urlEntidad(),'id'=>$entidad->id),
    'Hist&oacute;rico de transferencias'
);
?>

<dl class="nice contained tabs">
    <dd><a href="#" class="active">Hist&oacute;rico de transferencias</a></dd>
</dl>

<ul class="nice tabs-content contained">
    <li class="active" id="crear-cuenta">
        <div class="panel clearfix">
            <h5>Transferencias realizadas</h5>
            <p>A continuaci&oacute;n se presentan las &uacute;ltimas transferencias de fondos realizadas:</p>

            <?php
            $this->widget('zii.widgets.grid.CGridView', array(
                'dataProvider'=>$enviadas,
                'columns'=>array(
                    'id',
                    array(
                        'name'=>'Fecha transferencia',
                        'value'=>'app()->dateFormatter->format("dd\'/\'MM\'/\'y",$data->fecha_entrega)'
                    ),
                    array('name'=>'Usuario operador','value'=>'$data->operador->nombrePresentacion'),
                    array('name'=>'Destino','value'=>'$data->entidad->getTipoEntidad().": ".$data->entidad->getNombre()'),
                    array('name'=>'Cuenta origen','value'=>'$data->cuenta->identificador'),
                    array('name'=>'Monto','value'=>'app()->NumberFormatter->formatDecimal($data->monto)',
                          'htmlOptions'=>array('style' => 'text-align: right;')),
                )));
            ?>
        </div>

        <div class="panel clearfix">
            <h5>Transferencias recibidas</h5>
            <p>A continuaci&oacute;n se presentan las &uacute;ltimas transferencias de fondos recibidas:</p>

            <?php
            $this->widget('zii.widgets.grid.CGridView', array(
                'dataProvider'=>$recibidas,
                'columns'=>array(
                    'id',
                    array(
                        'name'=>'Fecha transferencia',
                        'value'=>'app()->dateFormatter->format("dd\'/\'MM\'/\'y",$data->fecha_entrega)'
                    ),
                    array('name'=>'Usuario operador','value'=>'$data->operador->nombrePresentacion'),
                    array('name'=>'Origen','value'=>'$data->entidadOrigen->getNombre()'),
                    array('name'=>'Cuenta origen','value'=>'$data->cuenta->identificador'),
                    array('name'=>'Monto','value'=>'app()->NumberFormatter->formatDecimal($data->monto)',
                          'htmlOptions'=>array('style' => 'text-align: right;')),
                )));
            ?>
        </div>

        <div class="panel clearfix">
            <h5>Transferencias internas</h5>
            <p>A continuaci&oacute;n se presentan las &uacute;ltimas transferencias internas de fondos:</p>

            <?php
            $this->widget('zii.widgets.grid.CGridView', array(
                'dataProvider'=>$internas,
                'columns'=>array(
                    'id',
                    array(
                        'name'=>'Fecha transferencia',
                        'value'=>'app()->dateFormatter->format("dd\'/\'MM\'/\'y",$data->fecha_transferencia)'
                    ),
                    array('name'=>'Usuario operador','value'=>'$data->operador->nombrePresentacion'),
                    array('name'=>'Cuenta origen','value'=>'$data->cuenta_origen->identificador'),
                    array('name'=>'Cuenta destino','value'=>'$data->cuenta_destino->identificador'),
                    array('name'=>'Monto','value'=>'app()->NumberFormatter->formatDecimal($data->monto)',
                        'htmlOptions'=>array('style' => 'text-align: right;')),
                )));
            ?>
        </div>

    </li>
</ul>