protected/modules/tareas/models/Tarea.php
<?php

/**
 * Modelo para la tabla "{{tarea}}".
 *
 * Los siguientes atributos estan disponibles desde la tabla '{{tarea}}':
 * @property integer $id
 * @property integer $entidad_id
 * @property string $tipo_entidad
 * @property string $titulo
 * @property string $fecha_inicio
 * @property string $fecha_termino
 * @property string $duracion
 * @property string $descripcion
 *
 * Las siguientes son las relaciones disponibles:
 * @property ParticipanteTarea[] $participanteTareas
 */
class Tarea extends CActiveRecord
{
	public $integrantes;
  public $archivos;
  public $caracteristicas_al_crear;
  
  /**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Tarea the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string la tabla asociada en la db
	 */
	public function tableName()
	{
		return '{{tarea}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		return array(
      array('entidad_id','required','on'=>'create'),
      array('entidad_id','numerical','integerOnly'=>true,'on'=>'create'),
	  array('titulo, categoria_id,duracion, descripcion, clasificacion,fecha_inicio,fecha_termino', 'required'),
      array('archivos','file','types'=>'pdf,jpg,gif,png,docx,xlsx','maxFiles'=>10,'maxSize'=>1024*1024*3,'allowEmpty'=>true),
	  array('categoria_id', 'numerical', 'integerOnly'=>true),
      array('tipo_entidad','in','range'=>array('iniciativa','proyecto'),'allowEmpty'=>false,'on'=>'create'),
	  array('publica','in','range'=>array('0','1'),'allowEmpty'=>false),
      array('fecha_inicio', 'date', 'format'=>'d-M-yyyy','allowEmpty'=>false),
      array('fecha_termino', 'date', 'format'=>'d-M-yyyy','allowEmpty'=>false),
	  array('titulo', 'length', 'max'=>45),
      array('duracion', 'length', 'max'=>5),
      array('integrantes','integrantesValidator','on'=>'create'),
      array('descripcion,caracteristicas_al_crear', 'safe'),
      //aqui se esta validando que el usuario que crea la tarea pertenezca a la entidad que selecciono
      array('entidad_id','pertenenciaEntidadValidator','on'=>'create'),
      //se valida que la fecha inicial sea antes que la fecha final
      array('fecha_inicio,fecha_termino','application.extensions.DatesValidator'),

			array('id, entidad_id, tipo_entidad, titulo, fecha_inicio, fecha_termino, duracion, descripcion', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array Relaciones del modeo.
	 */
	public function relations()
	{
		return array(
      'categoria_caracteristicas' => array(self::MANY_MANY, 'CategoriaActividad', '{{categoria_actividad_has_tarea}}(tarea_id, categoria_actividad_id)'),
      'caracteristicas' => array(self::HAS_MANY, 'CategoriaActividadHasTarea', 'tarea_id'),
      'ficheros' => array(self::HAS_MANY, 'TareaArchivo', 'tarea_id')
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'entidad_id' => 'Iniciativa o Proyecto',
			'tipo_entidad' => 'Tipo Entidad',
      'categoria_id' => 'Tipo de Actividad',
			'titulo' => 'Nombre de la actividad',
			'fecha_inicio' => 'Fecha Inicio',
			'fecha_termino' => 'Fecha Termino',
			'duracion' => 'Duracion (hrs.)',
			'descripcion' => 'Descripcion',
      'publica'=>'Visibilidad'
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		$criteria=new CDbCriteria;

		$criteria->compare('entidad_id',$this->entidad_id);
		$criteria->compare('tipo_entidad',$this->tipo_entidad,true);
		$criteria->compare('titulo',$this->titulo,true);
		$criteria->compare('fecha_inicio',$this->fecha_inicio,true);
		$criteria->compare('fecha_termino',$this->fecha_termino,true);
		$criteria->compare('duracion',$this->duracion,true);
		$criteria->compare('descripcion',$this->descripcion,true);
    
    $criteria->compare('t.aprobada',$this->aprobada);
    
    //debe tener un join con el participante actual
    $criteria->join='INNER JOIN {{participante_tarea}} p ON p.tarea_id=t.id';
    $criteria->compare('p.user_id',Yii::app()->user->id);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

  /**
   * Retrieves a list of models based on the current search/filter conditions.
   * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
   */
  public function generalSearch()
  {
    $criteria=new CDbCriteria;

    $criteria->compare('entidad_id',$this->entidad_id);
    $criteria->compare('tipo_entidad',$this->tipo_entidad,true);
    $criteria->compare('titulo',$this->titulo,true);
    $criteria->compare('fecha_inicio',$this->fecha_inicio,true);
    $criteria->compare('fecha_termino',$this->fecha_termino,true);
    $criteria->compare('duracion',$this->duracion,true);
    $criteria->compare('descripcion',$this->descripcion,true);
    
    $criteria->compare('t.aprobada',$this->aprobada);
    $criteria->compare('t.publica',$this->publica);

    return new CActiveDataProvider($this, array(
      'criteria'=>$criteria,
    ));
  }
  
  public function getCategorias()
  {
    return array(
      array('id'=>1,'nombre'=>'Actividad Administrativa'),
      array('id'=>2,'nombre'=>'Actividad T&eacute;cnica'),
    );
  }
  
  public function getCategoria()
  {
    $categorias = array(
      array('id'=>1,'nombre'=>'Actividad Administrativa'),
      array('id'=>2,'nombre'=>'Actividad T&eacute;cnica'),
    );
    return $categorias[$this->categoria_id-1];
  }
  
  public function getDuracionesDisponibles()
  {
    $duraciones=array();
    for($i=0;$i<30;$i++)
    {
      if(($i+1)*15<60)
        array_push($duraciones,array('id'=>15*($i+1),'nombre'=>15*($i+1).' min.'));
      else
        array_push($duraciones,array('id'=>15*($i+1),'nombre'=>((15*($i+1))/60).' hrs.'));
    }
    return $duraciones;
  }
  
  public function getParticipantes()
  {
    return ParticipanteTarea::model()->findAll('tarea_id=:tid',array(':tid'=>$this->id));
  }
  

  public function behaviors(){
    return array(
      'CTimestampBehavior' => array(
        'class' => 'zii.behaviors.CTimestampBehavior',
        'createAttribute' => 'fecha_ingreso',
        'updateAttribute' => 'fecha_actualizacion',
      ),
      'CAdvancedArBehavior' => array(
        'class' => 'application.extensions.CAdvancedArBehavior')
    );
  }
  
  public function beforeSave()
	{
		if(parent::beforeSave())
		{
      if(isset($this->fecha_inicio) && !empty($this->fecha_inicio))
        $this->fecha_inicio=date('Y-m-d', strtotime($this->fecha_inicio));
      if(isset($this->fecha_termino) && !empty($this->fecha_termino))
        $this->fecha_termino=date('Y-m-d', strtotime($this->fecha_termino));
      //debo settear la variable de usuario a mysql, se setea la id del usuario como el usuario logeado
      //o sea este usuario esta haciendo los cambios en la tabla de tareas
      $connection=Yii::app()->db; 
      $command=$connection->createCommand('SET @auth_uid='.Yii::app()->user->id);
      $command->execute();
      
      //cuando una tarea es creada o actualizada, todos los participantes deben tener su aprobacion en 0 (no aprobada)
      if(!$this->isNewRecord && $this->aceptada!=1)
      {
        foreach($this->participantes as $participante)
        {
          $participante->aprobada=0;
          $participante->save(false);
        }
      }
      
			return true;
		}
		else
			return false;
	}
  
  public function afterFind()
  {
    $this->fecha_inicio =  Yii::app()->dateFormatter->format("dd-MM-yyyy",$this->fecha_inicio);
    $this->fecha_termino =  Yii::app()->dateFormatter->format("dd-MM-yyyy",$this->fecha_termino);
    return parent::afterFind();
  }
  
  public function integrantesValidator($attribute,$params)
  {
    //verifico que al menos este el usuario logeado como integrante
    $integrantes = $this->integrantes;
    $have = false;
    
    if(count($integrantes)==0)
    {
      $this->addError('integrantes', 'Debes ingresar al menos 1 integrante para la actividad actual');
      return;
    }
    
    foreach($integrantes as $integrante)
    {
      if(Yii::app()->user->id == $integrante)
        $have=true;
    }
    
    if(!$have)
      $this->addError('integrantes', 'Debes ingresar al menos 1 integrante para la actividad actual');
  }

   //valida que el usuario que crea la actividad pertenezca a la entidad que selecciono para creacion
   public function pertenenciaEntidadValidator($attribute,$params)
   {
       if(!isset($this->entidad_id) || empty($this->entidad_id))
           return;
       if($this->tipo_entidad=='iniciativa')
       {
           $pertenece=IntegranteIniciativa::model()->find('iniciativa_id=:iid and user_id=:uid',array(
               ':iid'=>$this->entidad_id,
               ':uid'=>user()->id
           ));
           if($pertenece==null)
               $this->addError('entidad_id','No perteneces a la iniciativa seleccionada. Debes elegir una iniciativa de la cual seas integrante.');
       }
       elseif($this->tipo_entidad=='proyecto')
       {
           $pertenece=IntegranteProyecto::model()->find('proyecto_id=:pid and user_id=:uid',array(
               ':pid'=>$this->entidad_id,
               ':uid'=>user()->id
           ));
           if($pertenece==null)
               $this->addError('entidad_id','No perteneces al proyecto seleccionado. Debes elegir un proyecto del cual seas integrante.');
       }
       else
           $this->addError('tipo_entidad','Debes seleccionar ya sea una iniciativa o proyecto');
   }
  
  public function usuarioEsParticipante($id_usuario)
  {
    $participantes=$this->participantes;
    foreach($participantes as $participante)

protected/modules/tareas/views/crud/guardar.php
<?php
$this->pageTitle = 'Editar Actividad';
$this->breadcrumbs=array(
	'Actividades'=>array('index'),
	'Editar actividad',
);

?>

<dl class="nice contained tabs">
  <dd><a href="#" class="active">Editar actividad</a></dd>
</dl>

<ul class="nice tabs-content contained">
  <li class="active" id="crear-iniciativa">

    <div class="form">

    <?php $form=$this->beginWidget('foundation.widgets.FounActiveForm', array(
      'id'=>'actividad-form',
      'type'=>'nice',
      'htmlOptions'=>array('enctype'=>'multipart/form-data')
    )); ?>
    
      <?php echo $form->errorSummary($tarea); ?>
      <?php echo $form->errorSummary($original); ?>

      <div class="row">
        <div class="six columns">
          Iniciativa:
          <?php echo CHtml::dropDownList('iniciativa','', 
               CHtml::listData(Persona::model()->findByPk(Yii::app()->user->id)->iniciativas, 'id', 'nombre_abreviado'),
            array('style'=>'width:90%;','size'=>'8')); 
          ?> 
        </div>
        
        <div class="six columns">
          Proyecto:
          <?php echo CHtml::dropDownList('proyecto','', 
               CHtml::listData(Persona::model()->findByPk(Yii::app()->user->id)->proyectos, 'id', 'nombre'),
            array('style'=>'width:90%;','size'=>'8')); 
          ?> 
        </div>
        
        <input type="hidden" name="TareaTmp[entidad_id]" id="entidad_id">
        <input type="hidden" name="TareaTmp[tipo_entidad]" id="tipo_entidad">
      </div>
      
      <div class="row">
        <div class="six columns">
          <?php echo $form->textFieldRow($tarea,"titulo"); ?> 
        </div>
        
        <div class="six columns">
          <?php echo $form->dropDownListRow($tarea, 'categoria_id',
                CHtml::listData($tarea->categorias, 'id', 'nombre')
            ,array('style'=>'height: 28px;')); ?> 
        </div>
      </div>
      
      <p>
        <label for="integrantes" class="required">
          Integrantes: <span class="required">*</span>
        </label>
        <select id="integrantes" name="TareaTmp[integrantes]">
          <?php foreach($tarea->participantes as $participante):?>
            <option value="<?php echo $participante->user_id;?>" class="selected"><?php echo $participante->usuario->nombreCompleto;?></option>
          <?php endforeach;?>
        </select>
      </p>      
      
      <div class="row">
        <div class="four columns">
          <?php echo $form->labelEx($tarea,'fecha_inicio'); ?>
          <?php $this->widget('zii.widgets.jui.CJuiDatePicker',array(
            'model'=>$tarea,
            'attribute'=>'fecha_inicio',
            'options' => array('dateFormat'=>'dd-mm-yy'),
            'language'=>'es',
            'htmlOptions' => array('class'=>'input-text','style'=>'width:150px;'),
            ));
          ?>
          <div class="form-field error">
            <?php echo $form->error($tarea,'fecha_inicio'); ?>
          </div>
        </div>
        
        <div class="four columns">
          <?php echo $form->labelEx($tarea,'fecha_termino'); ?>
          <?php $this->widget('zii.widgets.jui.CJuiDatePicker',array(
            'model'=>$tarea,
            'attribute'=>'fecha_termino',
            'options' => array('dateFormat'=>'dd-mm-yy'),
            'language'=>'es',
            'htmlOptions' => array('class'=>'input-text','style'=>'width:150px;'),
            ));
          ?>
          <div class="form-field error">
            <?php echo $form->error($tarea,'fecha_termino'); ?>
          </div>
        </div>
        
        <div class="four columns">
          <?php echo $form->textFieldRow($tarea,"duracion",array('style'=>'width:150px;'));?>
        </div>
      </div>
      
      <fieldset>
        <h5>Caracter&iacute;sticas</h5>
        <p>Selecciona las caracter&iacute;sticas de la actividad a ingresar e ingresa un t&iacute;tulo de ser necesario.</p>
        
        <p style="margin-bottom:3px;">Caracter&iacute;stica:</p>
        <div class="row">
          <div class="four columns">
            <?php
              echo CHtml::dropDownList('nivel_1','', 
                   CHtml::listData(CategoriaActividad::model()->findAll('nivel=1'), 'id', 'nombre'),
              array('style'=>'height:28px;width:180px;')); 
            ?>
          </div>
          
          <div class="four columns">
            <?php
              echo CHtml::dropDownList('nivel_2','', 
                   CHtml::listData(CategoriaActividad::model()->findAll('nivel=2 and id_padre=1'), 'id', 'nombre'),
              array(
              'ajax' => array(
              'type'=>'POST',
              'url'=>CController::createUrl('utils/obtenerCategorias2'),
              'update'=>'#nivel_3',
              ),'style'=>'height:28px;width:180px;'));
            ?>
          </div>
          
          <div class="four columns">
            <?php
              echo CHtml::dropDownList('nivel_3','', 
                   CHtml::listData(CategoriaActividad::model()->findAll('nivel=3 and id_padre=3'), 'id', 'nombre'),
                   array('style'=>'height:28px;width:180px;')
              );
            ?>
          </div>
        </div>
        
        <div class="row">
          <div class="eight columns">
            T&iacute;tulo: <input type="text" name="titulo_actividad" id="titulo_actividad" class="input-text" style="width:420px;">
          </div>
          
          <div class="four columns">
            <a href="#" id="agregar-actividad-select" class="nice small radius green button" style="margin-top:19px;">Agregar</a>
          </div>
        </div>
        
        <div id="div-agregadas" class="row">
          <div class="twelve columns">
            <h5>Caracter&iacute;sticas agregadas</h5>
            <ul id="actividades-agregadas">
              <?php foreach($tarea->caracteristicas as $caracteristica):?>
                <li>
                  <?php echo $caracteristica->titulo;?>
                  <span class="span-actividad agregada-anterior red label" data-id="<?php echo $caracteristica->id;?>" style="cursor:pointer;float:right;margin-right:20px">Eliminar</span>
                </li>
              <?php endforeach;?>
            </ul>
          </div>
        </div>
      
      </fieldset>
      
      <p>
        Descripci&oacute;n: *<br>
        <?php $this->widget('application.extensions.redactorjs.Redactor', 
          array( 'lang' => 'en', 'toolbar' => 'mini', 'model' => $tarea, 'attribute' => 'descripcion' ));?>
      </p>
      <div class="row buttons">
        <?php echo CHtml::submitButton('Crear actividad',array('class'=>'nice radius medium button','id'=>'crear-actividad')); ?>
        <?php echo CHtml::submitButton('Guardar',array('class'=>'nice radius white medium button','id'=>'guardar-actividad')); ?>
      </div>

    <?php $this->endWidget(); ?>

    </div><!-- form -->
  </li>
</ul>

<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/jquery.fcbkcomplete.min.js', CClientScript::POS_HEAD);?>
<?php Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl.'/css/style.css');?>
<script type="text/javascript">
$(document).ready(function(){                
    $("#integrantes").fcbkcomplete({
        json_url: '<?php echo Yii::app()->createUrl('/usuarios/userActions/buscarIntegrante',array('mode'=>'json'));?>',
        addontab: true,                   
        maxitems: 10,
        input_min_size: 0,
        height: 10,
        cache: true,
        filter_selected:true,
        select_all_text: "seleccionar",
    });
    
    $('#agregar-actividad-select').click(function(){
      //se debe obtener el tipo de actividad
      var tipo_nombre=$('#nivel_3').find(':selected').text();
      var tipo_id=$('#nivel_3').find(':selected').val();
      var act_titulo=$('#titulo_actividad').val();
      var index=$('#actividades-agregadas li:last-child').index();
      if(index==-1)
        index=0;
      else
        index+=1;
      var elem='<li>'+tipo_nombre+' >> '+act_titulo+
        '<span class="span-actividad red label" style="cursor:pointer;float:right;margin-right:20px">'+
        'Eliminar'
        +'</span>'+
        '<input type="hidden" name="CategoriaActividadHasTarea['+index+'][categoria_actividad_id]" value="'+tipo_id+'">'+
        '<input type="hidden" name="CategoriaActividadHasTarea['+index+'][titulo]" value="'+act_titulo+'"></li>';
      $('#actividades-agregadas').append(elem);
      $('.span-actividad').bind('click', function() {
        $(this).parent().remove();
        return false;
      });
      $('#div-agregadas').removeClass('hide');
      return false;
    });
    
    $('#actividad-form').submit(function(){
       var iniciativa=$('#iniciativa').find(':selected').val();
       var proyecto=$('#proyecto').find(':selected').val();
       
       if(proyecto==undefined)
       {
         $('#entidad_id').val(iniciativa);
         $('#tipo_entidad').val('iniciativa');
       }
       else
       {
         $('#entidad_id').val(proyecto);
         $('#tipo_entidad').val('proyecto');
       }
     });
     
     $('#crear-actividad').click(function(){
      $('#actividad-form').attr('action','<?php echo Yii::app()->createUrl('/tareas/crud/crearEditada',array('id'=>$tarea->id));?>');
     });
     
     $('.agregada-anterior').click(function(){
      var elem=$(this);
      var id=$(this).attr('data-id');
      jQuery.ajax({
        'type':'POST',
        'url':'<?php echo Yii::app()->createUrl('/tareas/gestionActividades/eliminarCaracteristica');?>',
        'cache':false,
        'data':{'id':id},
        'success':function(html){
          alert(html);
          $(elem).parent().remove();
       }
       });
       return false;
     });
    
});
</script>

<?php Yii::app()->clientScript->registerScript('trigger_nivel3', 
  "jQuery(function($) {
  $('body').on('change','#nivel_1',function(){
     jQuery.ajax({'type':'POST','url':'".CController::createUrl('utils/obtenerCategorias1')."','cache':false,
     'data':jQuery(this).parents('form').serialize(),
     'success':function(html){
      jQuery('#nivel_2').html(html);
      //se actualiza tambien el nivel_3
      $('#nivel_2').trigger('change');
     }
     });
     return false;});
  });", 
CClientScript::POS_END);?>

protected/modules/tareas/views/crud/ver.php
<?php
$this->pageTitle = 'Ver Actividad';
$this->breadcrumbs=array(
	'Actividades'=>array('index'),
	$tarea->titulo
);

?>

<dl class="nice contained tabs">
  <dd><a href="#" class="active">Ver actividad</a></dd>
</dl>

<ul class="nice tabs-content contained">
  <li class="active" id="crear-iniciativa">

      <div class="row">
        <div class="eight columns">
          <p>
          <strong>Actividad registrada en:</strong> <?php echo $tarea->tipo_entidad;?>
          <?php if($tarea->tipo_entidad=='iniciativa'):?>
            <?php echo Iniciativa::model()->findByPk($tarea->entidad_id)->nombre_abreviado;?>
          <?php else:?>
            <?php echo Proyecto::model()->findByPk($tarea->entidad_id)->nombre;?>
          <?php endif;?><br>
          <?php if(isset($blame['usuario']->nombreCompleto)):?>
            <strong>&Uacute;ltima revisi&oacute;n por</strong>: <?php echo $blame['usuario']->nombreCompleto;?>
          <?php else:?>
            <strong>&Uacute;ltima revisi&oacute;n por</strong>: --
          <?php endif;?><br>
          <strong>Fecha &uacute;ltima revisi&oacute;n</strong>: <?php echo Yii::app()->dateFormatter->format("dd 'de' MMMM 'de' y 'a las' HH:mm:ss 'hrs.'",$blame['fecha']);?>
          </p>
        </div>
        
        <div class="four columns">
          <a href="<?php echo Yii::app()->createUrl('/tareas/gestionActividades/historialRevisiones',array('id'=>$tarea->id));?>" class="nice small button" style="float:right;">Ver historial de versiones</a>
          <?php if($mostrar_aprobacion && $tarea->aprobada==0 && $tarea->aceptada==1):?>
            <?php if($tarea->tipo_entidad=='iniciativa'):?>
              <p style="float:right;"><br><a href="<?php echo Yii::app()->createUrl('/tareas/supervision/aprobarActividad',array('id'=>$tarea->id));?>" class="nice green small button">Aprobar</a>
              <a href="#" data-reveal-id="myModal" class="nice red small button">Rechazar</a>
            <?php endif;?>
            <?php if($tarea->tipo_entidad=='proyecto' && $es_jefe_proyecto && $tarea->delegacion==null):?>
              <p style="float:right;"><br><a href="<?php echo Yii::app()->createUrl('/tareas/supervision/aprobarActividad',array('id'=>$tarea->id));?>" class="nice green small button">Aprobar</a>
              <a href="#" data-reveal-id="myModal" class="nice red small button">Rechazar</a>
              <br><br><a href="<?php echo url('/tareas/supervision/delegarDecision',array('id'=>$tarea->id));?>" class="nice small button">Delegar</a></p>
            <?php elseif($tarea->tipo_entidad=='proyecto' && !$es_jefe_proyecto && $tarea->delegacion!=null):?>
              <p style="float:right;"><br><a href="<?php echo Yii::app()->createUrl('/tareas/supervision/aprobarActividad',array('id'=>$tarea->id));?>" class="nice green small button">Aprobar</a>
              <a href="#" data-reveal-id="myModal" class="nice red small button">Rechazar</a>
            <?php endif;?>
          </p>
          <?php endif;?>
        </div>
      </div>
      
      <div class="panel">
        <h5>Actividad: <?php echo $tarea->titulo;?></h5>
        <p><?php echo $tarea->categoria['nombre'];?></p>
        <?php if($tarea->aprobada==-1):?>
          <p>
            Estado: <span style="color:red;">rechazada</span><br>
            <?php if(isset($tarea->comentarioRechazo['comentario'])):?>
              Motivo: <?php echo $tarea->comentarioRechazo['comentario'];?>
            <?php endif;?>
          </p>
        <?php endif;?>
        
        <div class="row">
          <div class="four columns">
            <strong>Fecha de inicio</strong>: <?php echo $tarea->fecha_inicio; ?>
          </div>
          
          <div class="four columns">
            <strong>Fecha de t&eacute;rmino</strong>: <?php echo $tarea->fecha_termino; ?>
          </div>
          
          <div class="four columns">
            <strong>Duraci&oacute;n</strong>: <?php echo $tarea->duracion;?> min.
          </div>
        </div>
        <br>
      </div>

      <?php $this->widget('ParticipantesWidget', array('participantes' => $tarea->participantes)); ?>
      
      <?php if($tarea->categoria_id==1):?>
        <div class="panel">
          <h5>Caracter&iacute;sticas</h5>
          <ul id="actividades-agregadas">
              <?php foreach($tarea->caracteristicas as $caracteristica):?>
                <li><?php echo $caracteristica->titulo;?></li>
              <?php endforeach;?>
            </ul>
        </div>
      <?php endif;?>

      <?php $this->widget('ArchivosWidget', array('archivos' => $tarea->ficheros)); ?>
      
      <div class="panel">
        <h5>Descripci&oacute;n</h5>
        <div style="border:1px #ccc dashed;background:#fff;padding:10px;"><?php echo $tarea->descripcion;?></div>
        <br>
      </div>
      
      <?php if($tarea->usuarioEsParticipante(Yii::app()->user->id) && !$tarea->usuarioEstadoAprobacion(Yii::app()->user->id)):?>
        <?php $this->widget('AccionesActividadWidget', array('tarea'=>$tarea));?>
      <?php endif;?>

  </li>
</ul>

<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/jquery.fcbkcomplete.min.js', CClientScript::POS_HEAD);?>
<?php Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl.'/css/style.css');?>
<script type="text/javascript">
$(document).ready(function(){                
    $("#integrantes").fcbkcomplete({
        json_url: '<?php echo Yii::app()->createUrl('');?>',
        addontab: true,                   
        maxitems: 10,
        input_min_size: 0,
        height: 10,
        cache: true,
        filter_selected:true,
        select_all_text: "seleccionar",
    });
});
</script>

<?php if($mostrar_aprobacion && $tarea->aprobada==0 && $tarea->aceptada==1){
$this->modal['id']='myModal';
$this->modal['close']=true;
$this->modal['content']=$this->renderPartial('/supervision/_rechazar_actividad',array('tarea'=>$tarea),true);
}
?>